backend:
  name: github
  repo: cityislander/test-gatsby-blog

media_folder: content/assets
public_folder: ../assets

collections:
  - name: 城市岛民
    label: 博客
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
